title = "The Archive"
theme = "private"
languagecode = "en"

pagination.pagerSize = 20

[params]
author = "Ji-Hoon Kim"
info = "Mathematician and Software Engineer"
description = "The archive that records everything"
keywords = "blog,personal,mathematician,software-engineer,developer"
avatarURL = "images/avatar.png"

faviconSVG = "images/favicon/favicon.svg"
favicon_32 = "images/favicon/favicon-32x32.png"
favicon_16 = "images/favicon/favicon-16x16.png"
touchIcon = "images/favicon/apple-touch-icon.png"

since = 2023
katex = true

[params.theme_config]
date_format = "2006-01-02"

[params.giscus] # https://giscus.app
repo = "bossm0n5t3r/blog-comments"
repoID = "MDEwOlJlcG9zaXRvcnkyMzYwNDc0NTQ="
category = "Announcements"
categoryID = "DIC_kwDODhHMXs4CYpdQ"
mapping = "pathname"
strict = "1"
reactionsEnabled = "1"
emitMetadata = "0"
inputPosition = "top"
theme = "light_high_contrast"
lang = "ko"
loading = "lazy"

[taxonomies]
category = "categories"
series = "series"
tag = "tags"
author = "authors"

[menu]
[[menu.main]]
identifier = "posts"
name = "Posts"
url = "/posts/"
weight = 1

[[menu.main]]
identifier = "categories"
name = "Categories"
url = "/categories/"
weight = 2

[[menu.main]]
identifier = "tags"
name = "Tags"
url = "/tags/"
weight = 3

[[menu.main]]
name = "Projects"
weight = 4
url = "projects/"

[[menu.main]]
name = "Books"
weight = 5
url = "books/"

[[menu.main]]
name = "About"
weight = 6
url = "about/"

[[menu.footer]]
name = "Github"
url = "https://github.com/bossm0n5t3r/"
weight = 1

[[menu.footer]]
name = "LinkedIn"
url = "https://www.linkedin.com/in/zhoon-kim/"
weight = 2


[markup.highlight]
anchorLineNos = true
lineAnchors = ''
lineNoStart = 1
lineNos = true
lineNumbersInTable = true
noClasses = true
style = 'github-dark'
tabWidth = 4

[markup]
[markup.goldmark]
renderer.unsafe = true
