title = "The Archive"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"
enableRobotsTXT = true

paginate = 20

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[params]
author = "Ji-Hoon Kim"
info = "Mathematician and Software Engineer"
description = "The archive that records everything"
keywords = "blog,personal,mathematician,software-engineer,developer"
avatarURL = "images/avatar.png"

faviconSVG = "images/favicon/favicon.svg"
favicon_32 = "images/favicon/favicon-32x32.png"
favicon_16 = "images/favicon/favicon-16x16.png"
touchIcon = "images/favicon/apple-touch-icon.png"

since = 2023

enableTwemoji = true
katex = true
colorScheme = "auto"
hidecolorschemetoggle = false

[params.giscus] # https://giscus.app
repo = "bossm0n5t3r/blog-comments"
repoID = "MDEwOlJlcG9zaXRvcnkyMzYwNDc0NTQ="
category = "Announcements"
categoryID = "DIC_kwDODhHMXs4CYpdQ"
mapping = "pathname"
strict = "1"
reactionsEnabled = "1"
emitMetadata = "0"
inputPosition = "top"
theme = "preferred-color-scheme"
lang = "ko"
loading = "lazy"

[taxonomies]
category = "categories"
series = "series"
tag = "tags"
author = "authors"

# Social links
[[params.social]]
name = "Github"
icon = "fa fa-github fa-2x"
weight = 1
url = "https://github.com/bossm0n5t3r/"

[[params.social]]
name = "LinkedIn"
icon = "fa-brands fa-linkedin fa-2x"
weight = 2
url = "https://www.linkedin.com/in/zhoon-kim/"

# Web Analytics
[services]
[services.googleAnalytics]
ID = "G-95QLXL4ME6"

# Menu links
#[[menu.main]]
#name = "About"
#weight = 1
#url = "about/"

[[menu.main]]
name = "Blog"
weight = 2
url = "posts/"

[[menu.main]]
name = "Projects"
weight = 3
url = "projects/"

[[menu.main]]
name = "Books"
weight = 4
url = "books/"

#
#[[menu.main]]
#name = "Contact me"
#weight = 10
#url = "contact/"

[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
style = "github-dark"
